name: adif
description: Amateur Data Interchange Format (ADIF) parser for Dart.
version: 315.2.0
repository: https://github.com/HeavySnowJakarta/dart-adif

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # `intl` is used for date formatting.
  intl: '>=0.16.0 <0.19.0'

  # `xml` is used for parsing ADX files.
  xml: ^6.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
