/// The implements of ADIF-defined QSO fields, generated by
/// `scripts/generate_qso_fields.dart`. Don't edit this file by hand.
library;

import '../data.dart';
import '../data_types/total.dart';

/// the contacted station's complete mailing address: full name, street address, city, postal code, and country
class Address extends AdifField {
  final AdifMultilineString value;
  
  Address(this.value) : super('ADDRESS');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Address fromString(String str) {
    return Address(AdifMultilineString.fromString(str));
  }
}

/// the contacted station's complete mailing address: full name, street address, city, postal code, and country
class AddressIntl extends AdifField {
  final AdifIntlMultilineString value;
  
  AddressIntl(this.value) : super('ADDRESS_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static AddressIntl fromString(String str) {
    return AddressIntl(AdifIntlMultilineString.fromString(str));
  }
}

/// the contacted station's callsign
class Call extends AdifField {
  final AdifString value;
  
  Call(this.value) : super('CALL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Call fromString(String str) {
    return Call(AdifString.fromString(str));
  }
}

/// contest check (e.g. for ARRL Sweepstakes)
class Check extends AdifField {
  final AdifString value;
  
  Check(this.value) : super('CHECK');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Check fromString(String str) {
    return Check(AdifString.fromString(str));
  }
}

/// contest class (e.g. for ARRL Field Day)
class Class extends AdifField {
  final AdifString value;
  
  Class(this.value) : super('CLASS');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Class fromString(String str) {
    return Class(AdifString.fromString(str));
  }
}

/// the date the QSO was last uploaded to the Club Log online service
class ClublogQsoUploadDate extends AdifField {
  final AdifDate value;
  
  ClublogQsoUploadDate(this.value) : super('CLUBLOG_QSO_UPLOAD_DATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static ClublogQsoUploadDate fromString(String str) {
    return ClublogQsoUploadDate(AdifDate.fromString(str));
  }
}

/// comment field for QSO
class Comment extends AdifField {
  final AdifString value;
  
  Comment(this.value) : super('COMMENT');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Comment fromString(String str) {
    return Comment(AdifString.fromString(str));
  }
}

/// comment field for QSO
class CommentIntl extends AdifField {
  final AdifIntlString value;
  
  CommentIntl(this.value) : super('COMMENT_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static CommentIntl fromString(String str) {
    return CommentIntl(AdifIntlString.fromString(str));
  }
}

/// the callsign of the individual operating the contacted station
class ContactedOp extends AdifField {
  final AdifString value;
  
  ContactedOp(this.value) : super('CONTACTED_OP');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static ContactedOp fromString(String str) {
    return ContactedOp(AdifString.fromString(str));
  }
}

/// QSO Contest Identifier
class ContestId extends AdifField {
  final AdifString value;
  
  ContestId(this.value) : super('CONTEST_ID');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static ContestId fromString(String str) {
    return ContestId(AdifString.fromString(str));
  }
}

/// the contacted station's DXCC entity name
class Country extends AdifField {
  final AdifString value;
  
  Country(this.value) : super('COUNTRY');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Country fromString(String str) {
    return Country(AdifString.fromString(str));
  }
}

/// the contacted station's DXCC entity name
class CountryIntl extends AdifField {
  final AdifIntlString value;
  
  CountryIntl(this.value) : super('COUNTRY_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static CountryIntl fromString(String str) {
    return CountryIntl(AdifIntlString.fromString(str));
  }
}

/// the contacted station's CQ Zone in the range 1 to 40 (inclusive)
class Cqz extends AdifField {
  final AdifPositiveInteger value;
  
  Cqz(this.value) : super('CQZ');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Cqz fromString(String str) {
    return Cqz(AdifPositiveInteger.fromString(str));
  }
}

/// date QSL received from DCL
class DclQslrdate extends AdifField {
  final AdifDate value;
  
  DclQslrdate(this.value) : super('DCL_QSLRDATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static DclQslrdate fromString(String str) {
    return DclQslrdate(AdifDate.fromString(str));
  }
}

/// date QSL sent to DCL
class DclQslsdate extends AdifField {
  final AdifDate value;
  
  DclQslsdate(this.value) : super('DCL_QSLSDATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static DclQslsdate fromString(String str) {
    return DclQslsdate(AdifDate.fromString(str));
  }
}

/// the contacted station's email address
class Email extends AdifField {
  final AdifString value;
  
  Email(this.value) : super('EMAIL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Email fromString(String str) {
    return Email(AdifString.fromString(str));
  }
}

/// the contacted station's owner's callsign
class EqCall extends AdifField {
  final AdifString value;
  
  EqCall(this.value) : super('EQ_CALL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static EqCall fromString(String str) {
    return EqCall(AdifString.fromString(str));
  }
}

/// date QSL received from eQSL.cc
class EqslQslrdate extends AdifField {
  final AdifDate value;
  
  EqslQslrdate(this.value) : super('EQSL_QSLRDATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static EqslQslrdate fromString(String str) {
    return EqslQslrdate(AdifDate.fromString(str));
  }
}

/// date QSL sent to eQSL.cc
class EqslQslsdate extends AdifField {
  final AdifDate value;
  
  EqslQslsdate(this.value) : super('EQSL_QSLSDATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static EqslQslsdate fromString(String str) {
    return EqslQslsdate(AdifDate.fromString(str));
  }
}

/// the contacted station's FISTS CW Club member number with a value greater than 0.
class Fists extends AdifField {
  final AdifPositiveInteger value;
  
  Fists(this.value) : super('FISTS');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Fists fromString(String str) {
    return Fists(AdifPositiveInteger.fromString(str));
  }
}

/// the contacted station's FISTS CW Club Century Certificate (CC) number with a value greater than 0.
class FistsCc extends AdifField {
  final AdifPositiveInteger value;
  
  FistsCc(this.value) : super('FISTS_CC');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static FistsCc fromString(String str) {
    return FistsCc(AdifPositiveInteger.fromString(str));
  }
}

/// "new EME ""initial"""
class ForceInit extends AdifField {
  final AdifBoolean value;
  
  ForceInit(this.value) : super('FORCE_INIT');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static ForceInit fromString(String str) {
    return ForceInit(AdifBoolean.fromString(str));
  }
}

/// import-only: use OPERATOR instead
class GuestOp extends AdifField {
  final AdifString value;
  
  GuestOp(this.value) : super('GUEST_OP');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static GuestOp fromString(String str) {
    return GuestOp(AdifString.fromString(str));
  }
}

/// the date the QSO was last uploaded to the HAMLOG.EU online service
class HamlogeuQsoUploadDate extends AdifField {
  final AdifDate value;
  
  HamlogeuQsoUploadDate(this.value) : super('HAMLOGEU_QSO_UPLOAD_DATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static HamlogeuQsoUploadDate fromString(String str) {
    return HamlogeuQsoUploadDate(AdifDate.fromString(str));
  }
}

/// the date the QSO was last uploaded to the HamQTH.com online service
class HamqthQsoUploadDate extends AdifField {
  final AdifDate value;
  
  HamqthQsoUploadDate(this.value) : super('HAMQTH_QSO_UPLOAD_DATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static HamqthQsoUploadDate fromString(String str) {
    return HamqthQsoUploadDate(AdifDate.fromString(str));
  }
}

/// the date the QSO was last uploaded to the HRDLog.net online service
class HrdlogQsoUploadDate extends AdifField {
  final AdifDate value;
  
  HrdlogQsoUploadDate(this.value) : super('HRDLOG_QSO_UPLOAD_DATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static HrdlogQsoUploadDate fromString(String str) {
    return HrdlogQsoUploadDate(AdifDate.fromString(str));
  }
}

/// the contacted station's IOTA Island Identifier, an 8-digit integer in the range 1 to 99999999 [leading zeroes optional]
class IotaIslandId extends AdifField {
  final AdifPositiveInteger value;
  
  IotaIslandId(this.value) : super('IOTA_ISLAND_ID');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static IotaIslandId fromString(String str) {
    return IotaIslandId(AdifPositiveInteger.fromString(str));
  }
}

/// the contacted station's ITU zone in the range 1 to 90 (inclusive)
class Ituz extends AdifField {
  final AdifPositiveInteger value;
  
  Ituz(this.value) : super('ITUZ');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Ituz fromString(String str) {
    return Ituz(AdifPositiveInteger.fromString(str));
  }
}

/// the geomagnetic K index at the time of the QSO in the range 0 to 9 (inclusive)
class KIndex extends AdifField {
  final AdifInteger value;
  
  KIndex(this.value) : super('K_INDEX');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static KIndex fromString(String str) {
    return KIndex(AdifInteger.fromString(str));
  }
}

/// the contacted station's latitude
class Lat extends AdifField {
  final AdifLocation value;
  
  Lat(this.value) : super('LAT');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Lat fromString(String str) {
    return Lat(AdifLocation.fromString(str));
  }
}

/// the contacted station's longitude
class Lon extends AdifField {
  final AdifLocation value;
  
  Lon(this.value) : super('LON');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Lon fromString(String str) {
    return Lon(AdifLocation.fromString(str));
  }
}

/// date QSL received from ARRL Logbook of the World
class LotwQslrdate extends AdifField {
  final AdifDate value;
  
  LotwQslrdate(this.value) : super('LOTW_QSLRDATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static LotwQslrdate fromString(String str) {
    return LotwQslrdate(AdifDate.fromString(str));
  }
}

/// date QSL sent to ARRL Logbook of the World
class LotwQslsdate extends AdifField {
  final AdifDate value;
  
  LotwQslsdate(this.value) : super('LOTW_QSLSDATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static LotwQslsdate fromString(String str) {
    return LotwQslsdate(AdifDate.fromString(str));
  }
}

/// details of the contacted station's Morse key (e.g. make, model, etc).
class MorseKeyInfo extends AdifField {
  final AdifString value;
  
  MorseKeyInfo(this.value) : super('MORSE_KEY_INFO');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MorseKeyInfo fromString(String str) {
    return MorseKeyInfo(AdifString.fromString(str));
  }
}

/// For Meteor Scatter QSOs, the name of the meteor shower in progress
class MsShower extends AdifField {
  final AdifString value;
  
  MsShower(this.value) : super('MS_SHOWER');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MsShower fromString(String str) {
    return MsShower(AdifString.fromString(str));
  }
}

/// the logging station's antenna
class MyAntenna extends AdifField {
  final AdifString value;
  
  MyAntenna(this.value) : super('MY_ANTENNA');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyAntenna fromString(String str) {
    return MyAntenna(AdifString.fromString(str));
  }
}

/// the logging station's antenna
class MyAntennaIntl extends AdifField {
  final AdifIntlString value;
  
  MyAntennaIntl(this.value) : super('MY_ANTENNA_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyAntennaIntl fromString(String str) {
    return MyAntennaIntl(AdifIntlString.fromString(str));
  }
}

/// the logging station's city
class MyCity extends AdifField {
  final AdifString value;
  
  MyCity(this.value) : super('MY_CITY');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyCity fromString(String str) {
    return MyCity(AdifString.fromString(str));
  }
}

/// the logging station's city
class MyCityIntl extends AdifField {
  final AdifIntlString value;
  
  MyCityIntl(this.value) : super('MY_CITY_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyCityIntl fromString(String str) {
    return MyCityIntl(AdifIntlString.fromString(str));
  }
}

/// the logging station's DXCC entity name
class MyCountry extends AdifField {
  final AdifString value;
  
  MyCountry(this.value) : super('MY_COUNTRY');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyCountry fromString(String str) {
    return MyCountry(AdifString.fromString(str));
  }
}

/// the logging station's DXCC entity name
class MyCountryIntl extends AdifField {
  final AdifIntlString value;
  
  MyCountryIntl(this.value) : super('MY_COUNTRY_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyCountryIntl fromString(String str) {
    return MyCountryIntl(AdifIntlString.fromString(str));
  }
}

/// the logging station's CQ Zone in the range 1 to 40 (inclusive)
class MyCqZone extends AdifField {
  final AdifPositiveInteger value;
  
  MyCqZone(this.value) : super('MY_CQ_ZONE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyCqZone fromString(String str) {
    return MyCqZone(AdifPositiveInteger.fromString(str));
  }
}

/// the logging station's FISTS CW Club member number with a value greater than 0.
class MyFists extends AdifField {
  final AdifPositiveInteger value;
  
  MyFists(this.value) : super('MY_FISTS');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyFists fromString(String str) {
    return MyFists(AdifPositiveInteger.fromString(str));
  }
}

/// the logging station's IOTA Island Identifier, an 8-digit integer in the range 1 to 99999999 [leading zeroes optional]
class MyIotaIslandId extends AdifField {
  final AdifPositiveInteger value;
  
  MyIotaIslandId(this.value) : super('MY_IOTA_ISLAND_ID');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyIotaIslandId fromString(String str) {
    return MyIotaIslandId(AdifPositiveInteger.fromString(str));
  }
}

/// the logging station's ITU zone in the range 1 to 90 (inclusive)
class MyItuZone extends AdifField {
  final AdifPositiveInteger value;
  
  MyItuZone(this.value) : super('MY_ITU_ZONE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyItuZone fromString(String str) {
    return MyItuZone(AdifPositiveInteger.fromString(str));
  }
}

/// the logging station's latitude
class MyLat extends AdifField {
  final AdifLocation value;
  
  MyLat(this.value) : super('MY_LAT');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyLat fromString(String str) {
    return MyLat(AdifLocation.fromString(str));
  }
}

/// the logging station's longitude
class MyLon extends AdifField {
  final AdifLocation value;
  
  MyLon(this.value) : super('MY_LON');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyLon fromString(String str) {
    return MyLon(AdifLocation.fromString(str));
  }
}

/// details of the logging station's Morse key (e.g. make, model, etc).
class MyMorseKeyInfo extends AdifField {
  final AdifString value;
  
  MyMorseKeyInfo(this.value) : super('MY_MORSE_KEY_INFO');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyMorseKeyInfo fromString(String str) {
    return MyMorseKeyInfo(AdifString.fromString(str));
  }
}

/// the logging operator's name
class MyName extends AdifField {
  final AdifString value;
  
  MyName(this.value) : super('MY_NAME');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyName fromString(String str) {
    return MyName(AdifString.fromString(str));
  }
}

/// the logging operator's name
class MyNameIntl extends AdifField {
  final AdifIntlString value;
  
  MyNameIntl(this.value) : super('MY_NAME_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyNameIntl fromString(String str) {
    return MyNameIntl(AdifIntlString.fromString(str));
  }
}

/// the logging station's postal code
class MyPostalCode extends AdifField {
  final AdifString value;
  
  MyPostalCode(this.value) : super('MY_POSTAL_CODE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyPostalCode fromString(String str) {
    return MyPostalCode(AdifString.fromString(str));
  }
}

/// the logging station's postal code
class MyPostalCodeIntl extends AdifField {
  final AdifIntlString value;
  
  MyPostalCodeIntl(this.value) : super('MY_POSTAL_CODE_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyPostalCodeIntl fromString(String str) {
    return MyPostalCodeIntl(AdifIntlString.fromString(str));
  }
}

/// description of the logging station's equipment
class MyRig extends AdifField {
  final AdifString value;
  
  MyRig(this.value) : super('MY_RIG');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyRig fromString(String str) {
    return MyRig(AdifString.fromString(str));
  }
}

/// description of the logging station's equipment
class MyRigIntl extends AdifField {
  final AdifIntlString value;
  
  MyRigIntl(this.value) : super('MY_RIG_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyRigIntl fromString(String str) {
    return MyRigIntl(AdifIntlString.fromString(str));
  }
}

/// special interest activity or event
class MySig extends AdifField {
  final AdifString value;
  
  MySig(this.value) : super('MY_SIG');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MySig fromString(String str) {
    return MySig(AdifString.fromString(str));
  }
}

/// special interest activity or event
class MySigIntl extends AdifField {
  final AdifIntlString value;
  
  MySigIntl(this.value) : super('MY_SIG_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MySigIntl fromString(String str) {
    return MySigIntl(AdifIntlString.fromString(str));
  }
}

/// special interest activity or event information
class MySigInfo extends AdifField {
  final AdifString value;
  
  MySigInfo(this.value) : super('MY_SIG_INFO');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MySigInfo fromString(String str) {
    return MySigInfo(AdifString.fromString(str));
  }
}

/// special interest activity or event information
class MySigInfoIntl extends AdifField {
  final AdifIntlString value;
  
  MySigInfoIntl(this.value) : super('MY_SIG_INFO_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MySigInfoIntl fromString(String str) {
    return MySigInfoIntl(AdifIntlString.fromString(str));
  }
}

/// the logging station's street
class MyStreet extends AdifField {
  final AdifString value;
  
  MyStreet(this.value) : super('MY_STREET');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyStreet fromString(String str) {
    return MyStreet(AdifString.fromString(str));
  }
}

/// the logging station's street
class MyStreetIntl extends AdifField {
  final AdifIntlString value;
  
  MyStreetIntl(this.value) : super('MY_STREET_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static MyStreetIntl fromString(String str) {
    return MyStreetIntl(AdifIntlString.fromString(str));
  }
}

/// the contacted station's operator's name
class Name extends AdifField {
  final AdifString value;
  
  Name(this.value) : super('NAME');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Name fromString(String str) {
    return Name(AdifString.fromString(str));
  }
}

/// the contacted station's operator's name
class NameIntl extends AdifField {
  final AdifIntlString value;
  
  NameIntl(this.value) : super('NAME_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static NameIntl fromString(String str) {
    return NameIntl(AdifIntlString.fromString(str));
  }
}

/// QSO notes
class Notes extends AdifField {
  final AdifMultilineString value;
  
  Notes(this.value) : super('NOTES');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Notes fromString(String str) {
    return Notes(AdifMultilineString.fromString(str));
  }
}

/// QSO notes
class NotesIntl extends AdifField {
  final AdifIntlMultilineString value;
  
  NotesIntl(this.value) : super('NOTES_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static NotesIntl fromString(String str) {
    return NotesIntl(AdifIntlMultilineString.fromString(str));
  }
}

/// the number of meteor scatter bursts heard by the logging station with a value greater than or equal to 0
class NrBursts extends AdifField {
  final AdifInteger value;
  
  NrBursts(this.value) : super('NR_BURSTS');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static NrBursts fromString(String str) {
    return NrBursts(AdifInteger.fromString(str));
  }
}

/// the number of meteor scatter pings heard by the logging station with a value greater than or equal to 0
class NrPings extends AdifField {
  final AdifInteger value;
  
  NrPings(this.value) : super('NR_PINGS');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static NrPings fromString(String str) {
    return NrPings(AdifInteger.fromString(str));
  }
}

/// the logging operator's callsign
class Operator extends AdifField {
  final AdifString value;
  
  Operator(this.value) : super('OPERATOR');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Operator fromString(String str) {
    return Operator(AdifString.fromString(str));
  }
}

/// the callsign of the owner of the station used to log the contact (the
class OwnerCallsign extends AdifField {
  final AdifString value;
  
  OwnerCallsign(this.value) : super('OWNER_CALLSIGN');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static OwnerCallsign fromString(String str) {
    return OwnerCallsign(AdifString.fromString(str));
  }
}

/// the contacted station's WPX prefix
class Pfx extends AdifField {
  final AdifString value;
  
  Pfx(this.value) : super('PFX');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Pfx fromString(String str) {
    return Pfx(AdifString.fromString(str));
  }
}

/// contest precedence (e.g. for ARRL Sweepstakes)
class Precedence extends AdifField {
  final AdifString value;
  
  Precedence(this.value) : super('PRECEDENCE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Precedence fromString(String str) {
    return Precedence(AdifString.fromString(str));
  }
}

/// public encryption key
class PublicKey extends AdifField {
  final AdifString value;
  
  PublicKey(this.value) : super('PUBLIC_KEY');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static PublicKey fromString(String str) {
    return PublicKey(AdifString.fromString(str));
  }
}

/// date QSO downloaded from QRZ.COM logbook
class QrzcomQsoDownloadDate extends AdifField {
  final AdifDate value;
  
  QrzcomQsoDownloadDate(this.value) : super('QRZCOM_QSO_DOWNLOAD_DATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QrzcomQsoDownloadDate fromString(String str) {
    return QrzcomQsoDownloadDate(AdifDate.fromString(str));
  }
}

/// the date the QSO was last uploaded to the QRZ.COM online service
class QrzcomQsoUploadDate extends AdifField {
  final AdifDate value;
  
  QrzcomQsoUploadDate(this.value) : super('QRZCOM_QSO_UPLOAD_DATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QrzcomQsoUploadDate fromString(String str) {
    return QrzcomQsoUploadDate(AdifDate.fromString(str));
  }
}

/// a message for the contacted station's operator to be incorporated in a paper or electronic QSL
class Qslmsg extends AdifField {
  final AdifMultilineString value;
  
  Qslmsg(this.value) : super('QSLMSG');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Qslmsg fromString(String str) {
    return Qslmsg(AdifMultilineString.fromString(str));
  }
}

/// a message for the contacted station's operator to be incorporated in a paper or electronic QSL
class QslmsgIntl extends AdifField {
  final AdifIntlMultilineString value;
  
  QslmsgIntl(this.value) : super('QSLMSG_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QslmsgIntl fromString(String str) {
    return QslmsgIntl(AdifIntlMultilineString.fromString(str));
  }
}

/// a message addressed to the logging station's operator incorporated in a paper or electronic QSL
class QslmsgRcvd extends AdifField {
  final AdifMultilineString value;
  
  QslmsgRcvd(this.value) : super('QSLMSG_RCVD');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QslmsgRcvd fromString(String str) {
    return QslmsgRcvd(AdifMultilineString.fromString(str));
  }
}

/// QSL received date
class Qslrdate extends AdifField {
  final AdifDate value;
  
  Qslrdate(this.value) : super('QSLRDATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Qslrdate fromString(String str) {
    return Qslrdate(AdifDate.fromString(str));
  }
}

/// QSL sent date
class Qslsdate extends AdifField {
  final AdifDate value;
  
  Qslsdate(this.value) : super('QSLSDATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Qslsdate fromString(String str) {
    return Qslsdate(AdifDate.fromString(str));
  }
}

/// the contacted station's QSL route
class QslVia extends AdifField {
  final AdifString value;
  
  QslVia(this.value) : super('QSL_VIA');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QslVia fromString(String str) {
    return QslVia(AdifString.fromString(str));
  }
}

/// date on which the QSO started
class QsoDate extends AdifField {
  final AdifDate value;
  
  QsoDate(this.value) : super('QSO_DATE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QsoDate fromString(String str) {
    return QsoDate(AdifDate.fromString(str));
  }
}

/// date on which the QSO ended
class QsoDateOff extends AdifField {
  final AdifDate value;
  
  QsoDateOff(this.value) : super('QSO_DATE_OFF');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QsoDateOff fromString(String str) {
    return QsoDateOff(AdifDate.fromString(str));
  }
}

/// indicates whether the QSO was random or scheduled
class QsoRandom extends AdifField {
  final AdifBoolean value;
  
  QsoRandom(this.value) : super('QSO_RANDOM');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QsoRandom fromString(String str) {
    return QsoRandom(AdifBoolean.fromString(str));
  }
}

/// the contacted station's city
class Qth extends AdifField {
  final AdifString value;
  
  Qth(this.value) : super('QTH');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Qth fromString(String str) {
    return Qth(AdifString.fromString(str));
  }
}

/// the contacted station's city
class QthIntl extends AdifField {
  final AdifIntlString value;
  
  QthIntl(this.value) : super('QTH_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static QthIntl fromString(String str) {
    return QthIntl(AdifIntlString.fromString(str));
  }
}

/// description of the contacted station's equipment
class Rig extends AdifField {
  final AdifMultilineString value;
  
  Rig(this.value) : super('RIG');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Rig fromString(String str) {
    return Rig(AdifMultilineString.fromString(str));
  }
}

/// description of the contacted station's equipment
class RigIntl extends AdifField {
  final AdifIntlMultilineString value;
  
  RigIntl(this.value) : super('RIG_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static RigIntl fromString(String str) {
    return RigIntl(AdifIntlMultilineString.fromString(str));
  }
}

/// signal report from the contacted station
class RstRcvd extends AdifField {
  final AdifString value;
  
  RstRcvd(this.value) : super('RST_RCVD');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static RstRcvd fromString(String str) {
    return RstRcvd(AdifString.fromString(str));
  }
}

/// signal report sent to the contacted station
class RstSent extends AdifField {
  final AdifString value;
  
  RstSent(this.value) : super('RST_SENT');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static RstSent fromString(String str) {
    return RstSent(AdifString.fromString(str));
  }
}

/// satellite mode - a code representing the satellite's uplink band and downlink band
class SatMode extends AdifField {
  final AdifString value;
  
  SatMode(this.value) : super('SAT_MODE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static SatMode fromString(String str) {
    return SatMode(AdifString.fromString(str));
  }
}

/// name of satellite
class SatName extends AdifField {
  final AdifString value;
  
  SatName(this.value) : super('SAT_NAME');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static SatName fromString(String str) {
    return SatName(AdifString.fromString(str));
  }
}

/// the solar flux at the time of the QSO in the range 0 to 300 (inclusive).
class Sfi extends AdifField {
  final AdifInteger value;
  
  Sfi(this.value) : super('SFI');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Sfi fromString(String str) {
    return Sfi(AdifInteger.fromString(str));
  }
}

/// the name of the contacted station's special activity or interest group
class Sig extends AdifField {
  final AdifString value;
  
  Sig(this.value) : super('SIG');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Sig fromString(String str) {
    return Sig(AdifString.fromString(str));
  }
}

/// the name of the contacted station's special activity or interest group
class SigIntl extends AdifField {
  final AdifIntlString value;
  
  SigIntl(this.value) : super('SIG_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static SigIntl fromString(String str) {
    return SigIntl(AdifIntlString.fromString(str));
  }
}

/// information associated with the contacted station's activity or interest group
class SigInfo extends AdifField {
  final AdifString value;
  
  SigInfo(this.value) : super('SIG_INFO');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static SigInfo fromString(String str) {
    return SigInfo(AdifString.fromString(str));
  }
}

/// information associated with the contacted station's activity or interest group
class SigInfoIntl extends AdifField {
  final AdifIntlString value;
  
  SigInfoIntl(this.value) : super('SIG_INFO_INTL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static SigInfoIntl fromString(String str) {
    return SigInfoIntl(AdifIntlString.fromString(str));
  }
}

/// 'Y' indicates that the contacted station's operator is now a Silent Key.
class SilentKey extends AdifField {
  final AdifBoolean value;
  
  SilentKey(this.value) : super('SILENT_KEY');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static SilentKey fromString(String str) {
    return SilentKey(AdifBoolean.fromString(str));
  }
}

/// the contacted station's Straight Key Century Club (SKCC) member information
class Skcc extends AdifField {
  final AdifString value;
  
  Skcc(this.value) : super('SKCC');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Skcc fromString(String str) {
    return Skcc(AdifString.fromString(str));
  }
}

/// contest QSO received serial number with a value greater than or equal to 0
class Srx extends AdifField {
  final AdifInteger value;
  
  Srx(this.value) : super('SRX');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Srx fromString(String str) {
    return Srx(AdifInteger.fromString(str));
  }
}

/// contest QSO received information
class SrxString extends AdifField {
  final AdifString value;
  
  SrxString(this.value) : super('SRX_STRING');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static SrxString fromString(String str) {
    return SrxString(AdifString.fromString(str));
  }
}

/// the logging station's callsign (the callsign used over the air)
class StationCallsign extends AdifField {
  final AdifString value;
  
  StationCallsign(this.value) : super('STATION_CALLSIGN');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static StationCallsign fromString(String str) {
    return StationCallsign(AdifString.fromString(str));
  }
}

/// contest QSO transmitted serial number with a value greater than or equal to 0
class Stx extends AdifField {
  final AdifInteger value;
  
  Stx(this.value) : super('STX');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Stx fromString(String str) {
    return Stx(AdifInteger.fromString(str));
  }
}

/// contest QSO transmitted information
class StxString extends AdifField {
  final AdifString value;
  
  StxString(this.value) : super('STX_STRING');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static StxString fromString(String str) {
    return StxString(AdifString.fromString(str));
  }
}

/// QSO Submode
class Submode extends AdifField {
  final AdifString value;
  
  Submode(this.value) : super('SUBMODE');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Submode fromString(String str) {
    return Submode(AdifString.fromString(str));
  }
}

/// indicates that the QSO information pertains to an SWL report
class Swl extends AdifField {
  final AdifBoolean value;
  
  Swl(this.value) : super('SWL');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Swl fromString(String str) {
    return Swl(AdifBoolean.fromString(str));
  }
}

/// Ten-Ten number with a value greater than 0
class TenTen extends AdifField {
  final AdifPositiveInteger value;
  
  TenTen(this.value) : super('TEN_TEN');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static TenTen fromString(String str) {
    return TenTen(AdifPositiveInteger.fromString(str));
  }
}

/// HHMM or HHMMSS in UTC
class TimeOff extends AdifField {
  final AdifTime value;
  
  TimeOff(this.value) : super('TIME_OFF');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static TimeOff fromString(String str) {
    return TimeOff(AdifTime.fromString(str));
  }
}

/// HHMM or HHMMSS in UTC
class TimeOn extends AdifField {
  final AdifTime value;
  
  TimeOn(this.value) : super('TIME_ON');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static TimeOn fromString(String str) {
    return TimeOn(AdifTime.fromString(str));
  }
}

/// the contacted station's UKSMG member number with a value greater than 0
class Uksmg extends AdifField {
  final AdifPositiveInteger value;
  
  Uksmg(this.value) : super('UKSMG');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Uksmg fromString(String str) {
    return Uksmg(AdifPositiveInteger.fromString(str));
  }
}

/// import-only: use STATE instead
class VeProv extends AdifField {
  final AdifString value;
  
  VeProv(this.value) : super('VE_PROV');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static VeProv fromString(String str) {
    return VeProv(AdifString.fromString(str));
  }
}

/// the contacted station's URL
class Web extends AdifField {
  final AdifString value;
  
  Web(this.value) : super('WEB');
  
  @override
  String getString() {
    return value.getString();
  }
  
  static Web fromString(String str) {
    return Web(AdifString.fromString(str));
  }
}

